version: '3.8'

services:
    adminer:
        image: adminer
        ports:
            - '${ADMINER_PORT}:8080'

    mailhog:
        image: mailhog/mailhog
        ports:
            - '${MAILHOG_SMTP_PORT}:1025'
            - '${MAILHOG_UI_PORT}:8025'
    
    nginx:
        build:
            context: ./nginx
            #args:
            #   APP_ENV: '1234'
        working_dir: ${WORKING_DIR}
        volumes:
            - ./../:${WORKING_DIR}
            #- ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
#        environment: # @todo
#            VIRTUAL_HOST:
#            NGINX_HOST:
        ports:
            - '${WEB_PORT}:80'
    
    php-cli:
        ports:
            - '8000:8000' # default symfony serve cli port
        
    php-fpm:
        #build: ./php-fpm_dev # тут xDebug, который можно включить локально в docker-compose.local.yml
#        build: ./php-fpm-alpine
        volumes:
            - ./../:${WORKING_DIR}
            - ./php-fpm_dev/global.ini:/usr/local/etc/php/conf.d/global.ini
#            - ./php-fpm_dev/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        environment:
            APP_ENV: dev
            APP_DEBUG: 1

    rabbitmq:
        build: ./rabbitmq-management
        hostname: ${APP_ENV}
        volumes:
            - rabbitmq:/var/lib/rabbitmq/
            - ./rabbitmq-management/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
            - ./../var/rabbitmq/${APP_ENV}_logs/:/var/log/rabbitmq/
            - ./rabbitmq-management/.bashrc:/var/lib/rabbitmq/.bashrc
        ports:
            - '${RABBITMQ_PORT}:5672'
            - '${RABBITMQ_MANAGER_PORT}:15672'

    redis-commander:
        image: rediscommander/redis-commander:latest
        environment:
            REDIS_HOSTS: local:redis:6379
        ports:
            - '${REDIS_COMMANDER_PORT}:8081'

volumes:
    rabbitmq:
